// src/lib/syllabus.ts

export const syllabusData = {
  neet: {
    subjects: [
      {
        name: 'Physics',
        chapters: [
          { name: 'Physical World and Measurement', topics: ['Units and Measurements', 'Dimensions of Physical Quantities'] },
          { name: 'Kinematics', topics: ['Motion in a Straight Line', 'Motion in a Plane'] },
          { name: 'Laws of Motion', topics: ["Newton's Laws of Motion", 'Friction'] },
          { name: 'Work, Energy, and Power', topics: ['Work done by a Constant Force and a Variable Force', 'Kinetic and Potential Energies', 'Power'] },
          { name: 'Motion of System of Particles and Rigid Body', topics: ['Centre of Mass', 'Moment of a Force, Torque, Angular Momentum'] },
          { name: 'Gravitation', topics: ["Kepler's Laws of Planetary Motion", 'The Universal Law of Gravitation'] },
          { name: 'Properties of Bulk Matter', topics: ['Elastic behaviour, Stress-strain relationship', 'Viscosity, Stokes\' law'] },
          { name: 'Thermodynamics', topics: ['Thermal Equilibrium', 'First law of thermodynamics', 'Second law of thermodynamics'] },
          { name: 'Behaviour of Perfect Gas and Kinetic Theory', topics: ['Equation of State of a Perfect Gas', 'Kinetic Theory of Gases'] },
          { name: 'Oscillations and Waves', topics: ['Periodic Motion', 'Simple Harmonic Motion (SHM)', 'Wave motion'] },
          { name: 'Electrostatics', topics: ['Electric Charges and their Conservation', 'Coulomb\'s Law', 'Electric Field', 'Electric Potential'] },
          { name: 'Current Electricity', topics: ['Electric Current', 'Ohm\'s Law', 'Kirchhoff\'s laws and simple applications'] },
          { name: 'Magnetic Effects of Current and Magnetism', topics: ['Concept of Magnetic Field', 'Biot-Savart Law', 'Ampere\'s Law', 'Magnetic dipole moment'] },
          { name: 'Electromagnetic Induction and Alternating Currents', topics: ['Electromagnetic Induction; Faraday\'s Law', 'Alternating Currents'] },
          { name: 'Electromagnetic Waves', topics: ['Electromagnetic Waves and their Characteristics'] },
          { name: 'Optics', topics: ['Reflection of Light', 'Refraction of Light', 'Optical Instruments', 'Wave Optics'] },
          { name: 'Dual Nature of Matter and Radiation', topics: ['Dual nature of radiation', 'Photoelectric effect', 'Matter waves-wave nature of particles'] },
          { name: 'Atoms and Nuclei', topics: ['Atoms', 'Nuclei', 'Radioactivity'] },
          { name: 'Electronic Devices', topics: ['Energy bands in solids (qualitative ideas only)', 'Semiconductor Diode- I-V characteristics', 'Logic gates'] },
        ],
      },
      {
        name: 'Chemistry',
        chapters: [
          { name: 'Some Basic Concepts of Chemistry', topics: ['General Introduction', 'Laws of Chemical Combination', 'Dalton\'s Atomic Theory', 'Concept of elements, atoms and molecules', 'Atomic and molecular masses', 'Mole concept and molar mass'] },
          { name: 'Structure of Atom', topics: ['Atomic Number, isotopes and isobars', 'Concept of shells and subshells', 'Dual nature of matter and light', 'de Broglie\'s relationship', 'Heisenberg uncertainty principle', 'Concept of orbital'] },
          { name: 'Classification of Elements and Periodicity in Properties', topics: ['Modern Periodic Law and long form of Periodic Table', 'Periodic trends in properties of elements-atomic radii, ionic radii, inert gas radii, Ionization enthalpy, electron gain enthalpy, electronegativity, valency'] },
          { name: 'Chemical Bonding and Molecular Structure', topics: ['Valence electrons, ionic bond, covalent bond, bond parameters', 'Lewis structure, polar character of covalent bond, covalent character of ionic bond', 'VSEPR theory', 'Hybridization'] },
          { name: 'States of Matter: Gases and Liquids', topics: ['Three states of matter, intermolecular interactions', 'Gas laws', 'Ideal gas equation', 'Liquid State- Vapour pressure, viscosity and surface tension'] },
          { name: 'Thermodynamics', topics: ['Concepts of System, types of systems, surroundings', 'First law of thermodynamics-internal energy and enthalpy', 'Second law of Thermodynamics', 'Third law of thermodynamics'] },
          { name: 'Equilibrium', topics: ['Equilibrium in physical and chemical processes', 'Law of chemical equilibrium', 'Le Chatelier\'s principle', 'Ionic equilibrium- ionization of acids and bases', 'Buffer solutions'] },
          { name: 'Redox Reactions', topics: ['Concept of oxidation and reduction', 'Redox reactions', 'Oxidation number', 'Balancing redox reactions'] },
          { name: 'Hydrogen', topics: ['Position of hydrogen in periodic table, occurrence, isotopes', 'Preparation, properties and uses of hydrogen', 'Hydrides-ionic, covalent and interstitial'] },
          { name: 's-Block Elements (Alkali and Alkaline earth metals)', topics: ['Group 1 and Group 2 elements', 'General introduction, electronic configuration, occurrence', 'Anomalous properties of the first element of each group'] },
          { name: 'Some p-Block Elements', topics: ['General Introduction to p-Block Elements', 'Group 13 elements', 'Group 14 elements'] },
          { name: 'Organic Chemistry- Some Basic Principles and Techniques', topics: ['General introduction, methods of purification, qualitative and quantitative analysis', 'Classification and IUPAC nomenclature of organic compounds', 'Electronic displacements in a covalent bond'] },
          { name: 'Hydrocarbons', topics: ['Classification of Hydrocarbons', 'Alkanes', 'Alkenes', 'Alkynes', 'Aromatic hydrocarbons'] },
          { name: 'Solid State', topics: ['Classification of solids based on different binding forces', 'Amorphous and crystalline solids', 'Unit cell in two dimensional and three dimensional lattices'] },
          { name: 'Solutions', topics: ['Types of solutions, expression of concentration of solutions of solids in liquids', 'Solubility of gases in liquids', 'Colligative properties'] },
          { name: 'Electrochemistry', topics: ['Redox reactions, conductance in electrolytic solutions', 'Electrolytic cells and Galvanic cells', 'Lead accumulator, fuel cells'] },
          { name: 'Chemical Kinetics', topics: ['Rate of a reaction (average and instantaneous)', 'Factors affecting rates of reaction', 'Order and molecularity of a reaction'] },
          { name: 'Surface Chemistry', topics: ['Adsorption', 'Catalysis', 'Colloidal state'] },
          { name: 'General Principles and Processes of Isolation of Elements', topics: ['Principles and methods of extraction', 'Thermodynamic principles of metallurgy'] },
          { name: 'p- Block Elements', topics: ['Group 15 elements', 'Group 16 elements', 'Group 17 elements', 'Group 18 elements'] },
          { name: 'd and f Block Elements', topics: ['General introduction, electronic configuration, occurrence and characteristics of transition metals', 'Lanthanoids', 'Actinoids'] },
          { name: 'Coordination Compounds', topics: ['Introduction, ligands, coordination number, colour, magnetic properties and shapes', 'IUPAC nomenclature of mononuclear coordination compounds'] },
          { name: 'Haloalkanes and Haloarenes', topics: ['Haloalkanes: Nomenclature, nature of C-X bond, physical and chemical properties', 'Haloarenes: Nature of C-X bond, substitution reactions'] },
          { name: 'Alcohols, Phenols and Ethers', topics: ['Alcohols: Nomenclature, methods of preparation, physical and chemical properties', 'Phenols: Nomenclature, methods of preparation, physical and chemical properties', 'Ethers: Nomenclature, methods of preparation, physical and chemical properties'] },
          { name: 'Aldehydes, Ketones and Carboxylic Acids', topics: ['Aldehydes and Ketones: Nomenclature, nature of carbonyl group, methods of preparation', 'Carboxylic Acids: Nomenclature, acidic nature, methods of preparation'] },
          { name: 'Organic Compounds Containing Nitrogen', topics: ['Amines: Nomenclature, classification, structure, methods of preparation', 'Cyanides and Isocyanides', 'Diazonium salts'] },
          { name: 'Biomolecules', topics: ['Carbohydrates', 'Proteins', 'Vitamins', 'Nucleic Acids'] },
          { name: 'Polymers', topics: ['Classification- Natural and synthetic', 'Methods of polymerization (addition and condensation)'] },
          { name: 'Chemistry in Everyday Life', topics: ['Chemicals in medicines', 'Chemicals in food', 'Cleansing agents'] },
        ],
      },
      {
        name: 'Biology',
        chapters: [
          { name: 'Diversity in Living World', topics: ['What is living? ; Biodiversity; Need for classification', 'Three domains of life', 'Taxonomy & Systematics', 'Concept of species and taxonomical hierarchy'] },
          { name: 'Biological Classification', topics: ['Five kingdom classification', 'Salient features and classification of Monera, Protista and Fungi into major groups', 'Lichens; Viruses and Viroids'] },
          { name: 'Plant Kingdom', topics: ['Classification of plants into major groups', 'Salient and distinguishing features of Algae, Bryophytes, Pteridophytes, Gymnosperms'] },
          { name: 'Animal Kingdom', topics: ['Salient features and classification of animals-nonchordate up to phyla level and chordate up to classes level'] },
          { name: 'Morphology of Flowering Plants', topics: ['Morphology and modifications', 'Tissues', 'Anatomy and functions of different parts of flowering plants: Root, stem, leaf, inflorescence- cymose and recemose, flower, fruit and seed'] },
          { name: 'Structural Organisation in Animals', topics: ['Animal tissues', 'Morphology, anatomy and functions of different systems (digestive, circulatory, respiratory, nervous and reproductive) of an insect (cockroach)'] },
          { name: 'Cell-The Unit of Life', topics: ['Cell theory and cell as the basic unit of life', 'Structure of prokaryotic and eukaryotic cell', 'Plant cell and animal cell', 'Cell envelope, cell membrane, cell wall'] },
          { name: 'Biomolecules', topics: ['Chemical constituents of living cells: biomolecules, structure and function of proteins, carbohydrates, lipids, nucleic acids', 'Enzymes- types, properties, enzyme action'] },
          { name: 'Cell Cycle and Cell Division', topics: ['Cell cycle, mitosis, meiosis and their significance'] },
          { name: 'Transport in Plants', topics: ['Movement of water, gases and nutrients', 'Cell to cell transport-Diffusion, facilitated diffusion, active transport', 'Plant-water relations- Imbibition, water potential, osmosis, plasmolysis'] },
          { name: 'Mineral Nutrition', topics: ['Essential minerals, macro and micronutrients and their role', 'Deficiency symptoms', 'Mineral toxicity'] },
          { name: 'Photosynthesis in Higher Plants', topics: ['Photosynthesis as a means of Autotrophic nutrition', 'Site of photosynthesis, pigments involved in Photosynthesis (Elementary idea)', 'Photochemical and biosynthetic phases of photosynthesis'] },
          { name: 'Respiration in Plants', topics: ['Exchange of gases', 'Cellular respiration - glycolysis, fermentation (anaerobic), TCA cycle and electron transport system (aerobic)'] },
          { name: 'Plant Growth and Development', topics: ['Seed germination', 'Phases of plant growth and plant growth rate', 'Conditions of growth', 'Differentiation, dedifferentiation and redifferentiation'] },
          { name: 'Digestion and Absorption', topics: ['Alimentary canal and digestive glands', 'Role of digestive enzymes and gastrointestinal hormones', 'Peristalsis, digestion, absorption and assimilation of proteins, carbohydrates and fats'] },
          { name: 'Breathing and Exchange of Gases', topics: ['Respiratory organs in animals (recall only)', 'Respiratory system in humans', 'Mechanism of breathing and its regulation in humans-exchange of gases, transport of gases and regulation of respiration'] },
          { name: 'Body Fluids and Circulation', topics: ['Composition of blood, blood groups, coagulation of blood', 'Composition of lymph and its function', 'Human circulatory system'] },
          { name: 'Excretory Products and their Elimination', topics: ['Modes of excretion - Ammonotelism, ureotelism, uricotelism', 'Human excretory system-structure and function', 'Urine formation, Osmoregulation'] },
          { name: 'Locomotion and Movement', topics: ['Types of movement - ciliary, flagellar, muscular', 'Skeletal system and its functions', 'Joints', 'Disorders of muscular and skeletal system'] },
          { name: 'Neural Control and Coordination', topics: ['Neuron and nerves', 'Nervous system in humans- central nervous system, peripheral nervous system and visceral nervous system', 'Generation and conduction of nerve impulse'] },
          { name: 'Chemical Coordination and Integration', topics: ['Endocrine glands and hormones', 'Human endocrine system-Hypothalamus, Pituitary, Pineal, Thyroid, Parathyroid, Adrenal, Pancreas, Gonads'] },
          { name: 'Reproduction in Organisms', topics: ['Reproduction, a characteristic feature of all organisms for continuation of species', 'Modes of reproduction - Asexual and sexual', 'Asexual reproduction'] },
          { name: 'Sexual Reproduction in Flowering Plants', topics: ['Flower structure', 'Development of male and female gametophytes', 'Pollination-types, agencies and examples'] },
          { name: 'Human Reproduction', topics: ['Male and female reproductive systems', 'Microscopic anatomy of testis and ovary', 'Gametogenesis-spermatogenesis & oogenesis'] },
          { name: 'Reproductive Health', topics: ['Need for reproductive health and prevention of sexually transmitted diseases (STD)', 'Birth control-Need and Methods, Contraception and Medical Termination of Pregnancy (MTP)'] },
          { name: 'Heredity and variation', topics: ['Mendelian Inheritance', 'Deviations from Mendelism-Incomplete dominance, Co-dominance, Multiple alleles and Inheritance of blood groups, Pleiotropy'] },
          { name: 'Molecular Basis of Inheritance', topics: ['Search for genetic material and DNA as genetic material', 'Structure of DNA and RNA', 'DNA packaging', 'DNA replication'] },
          { name: 'Evolution', topics: ['Origin of life', 'Biological evolution and evidences for biological evolution from Paleontology, comparative anatomy, embryology and molecular evidence', 'Darwins contribution, Modern Synthetic theory of Evolution'] },
          { name: 'Human Health and Disease', topics: ['Pathogens; parasites causing human diseases (Malaria, Filariasis, Ascariasis, Typhoid, Pneumonia, common cold, amoebiasis, ring worm)', 'Basic concepts of immunology-vaccines', 'Cancer, HIV and AIDS'] },
          { name: 'Strategies for Enhancement in Food Production', topics: ['Improvement in food production', 'Plant breeding, tissue culture, single cell protein, Biofortification', 'Apiculture and Animal husbandry'] },
          { name: 'Microbes in Human Welfare', topics: ['In household food processing, industrial production, sewage treatment, energy generation and as biocontrol agents and biofertilizers'] },
          { name: 'Biotechnology: Principles and Processes', topics: ['Genetic engineering (Recombinant DNA technology)'] },
          { name: 'Biotechnology and Its Applications', topics: ['Application of Biotechnology in health and agriculture', 'Human insulin and vaccine production, gene therapy', 'Genetically modified organisms-Bt crops; Transgenic Animals'] },
          { name: 'Organisms and Populations', topics: ['Organisms and environment: Habitat and niche, Population and ecological adaptations', 'Population interactions-mutualism, competition, predation, parasitism'] },
          { name: 'Ecosystem', topics: ['Ecosystems: Patterns, components; productivity and decomposition', 'Energy flow', 'Pyramids of number, biomass, energy'] },
          { name: 'Biodiversity and its Conservation', topics: ['Concept of Biodiversity', 'Patterns of Biodiversity', 'Importance of Biodiversity', 'Loss of Biodiversity', 'Biodiversity conservation'] },
          { name: 'Environmental Issues', topics: ['Air pollution and its control', 'Water pollution and its control', 'Agrochemicals and their effects', 'Solid waste management', 'Radioactive waste management'] },
        ],
      },
    ],
  },
  jee: {
    subjects: [
       {
        name: 'Physics',
        chapters: [
          { name: 'Physics and Measurement', topics: ['Units of measurements', 'System of Units', 'S I Units', 'dimensional analysis'] },
          { name: 'Kinematics', topics: ['Kinematics in one dimension', 'two dimensions and three dimensions', 'projectiles'] },
          { name: 'Laws of Motion', topics: ['Newton’s laws of motion', 'conservation of linear momentum', 'friction'] },
          { name: 'Work, Energy and Power', topics: ['Work-energy theorem', 'conservative and non-conservative forces', 'potential energy', 'power'] },
          { name: 'Rotational Motion', topics: ['Moment of inertia', 'torque', 'angular momentum', 'conservation of angular momentum', 'rolling motion'] },
          { name: 'Gravitation', topics: ['Newton’s law of gravitation', 'gravitational potential energy', 'Kepler’s laws', 'escape velocity'] },
          { name: 'Properties of Solids and Liquids', topics: ['Hooke’s law', 'Young’s modulus', 'Pascal’s law', 'Bernoulli’s principle', 'viscosity', 'surface tension'] },
          { name: 'Thermodynamics', topics: ['Zeroth, First and Second laws of thermodynamics', 'isothermal and adiabatic processes', 'Carnot engine'] },
          { name: 'Kinetic Theory of Gases', topics: ['Ideal gas', 'kinetic theory', 'degrees of freedom', 'mean free path'] },
          { name: 'Oscillations and Waves', topics: ['Simple harmonic motion', 'damped and forced oscillations', 'wave motion', 'Doppler effect'] },
          { name: 'Electrostatics', topics: ['Coulomb’s law', 'electric field', 'Gauss’s law', 'electric potential', 'capacitors'] },
          { name: 'Current Electricity', topics: ['Ohm’s law', 'Kirchhoff’s laws', 'resistors in series and parallel', 'potentiometer'] },
          { name: 'Magnetic Effects of Current and Magnetism', topics: ['Biot-Savart law', 'Ampere’s law', 'Lorentz force', 'magnetic materials'] },
          { name: 'Electromagnetic Induction and Alternating Currents', topics: ['Faraday’s law', 'Lenz’s law', 'LCR circuit', 'transformers'] },
          { name: 'Electromagnetic Waves', topics: ['Displacement current', 'electromagnetic spectrum'] },
          { name: 'Optics', topics: ['Reflection and refraction of light', 'lenses', 'microscopes and telescopes', 'interference', 'diffraction', 'polarization'] },
          { name: 'Dual Nature of Matter and Radiation', topics: ['Photoelectric effect', 'de Broglie hypothesis', 'Davisson-Germer experiment'] },
          { name: 'Atoms and Nuclei', topics: ['Bohr model', 'hydrogen spectrum', 'radioactivity', 'nuclear fission and fusion'] },
          { name: 'Electronic Devices', topics: ['Semiconductors', 'p-n junction diode', 'transistors', 'logic gates'] },
          { name: 'Communication Systems', topics: ['Modulation', 'amplitude and frequency modulation', 'bandwidth of signals'] },
        ],
      },
      {
        name: 'Chemistry',
        chapters: [
          { name: 'Some Basic Concepts in Chemistry', topics: ['Mole concept', 'stoichiometry', 'concentration terms'] },
          { name: 'States of Matter', topics: ['Gaseous state', 'liquid state', 'solid state'] },
          { name: 'Atomic Structure', topics: ['Bohr’s model', 'quantum mechanical model', 'orbitals', 'quantum numbers'] },
          { name: 'Chemical Bonding and Molecular Structure', topics: ['Ionic bond', 'covalent bond', 'VSEPR theory', 'hybridization', 'molecular orbital theory'] },
          { name: 'Chemical Thermodynamics', topics: ['First, second and third laws of thermodynamics', 'enthalpy', 'entropy', 'Gibbs free energy'] },
          { name: 'Solutions', topics: ['Colligative properties', 'Raoult’s law', 'van’t Hoff factor'] },
          { name: 'Equilibrium', topics: ['Chemical equilibrium', 'ionic equilibrium', 'pH', 'buffer solutions', 'solubility product'] },
          { name: 'Redox Reactions and Electrochemistry', topics: ['Oxidation number', 'balancing of redox reactions', 'electrochemical cells', 'Nernst equation'] },
          { name: 'Chemical Kinetics', topics: ['Rate of reaction', 'order and molecularity', 'Arrhenius equation'] },
          { name: 'Surface Chemistry', topics: ['Adsorption', 'colloids', 'emulsions'] },
          { name: 'Classification of Elements and Periodicity in Properties', topics: ['Periodic table', 'periodic trends'] },
          { name: 'General Principles and Processes of Isolation of Metals', topics: ['Metallurgy', 'extraction of metals'] },
          { name: 'Hydrogen', topics: ['Position in periodic table', 'isotopes', 'properties of hydrogen'] },
          { name: 's-Block Elements', topics: ['Alkali metals', 'alkaline earth metals'] },
          { name: 'p-Block Elements', topics: ['Groups 13 to 18'] },
          { name: 'd-and f-Block Elements', topics: ['Transition elements', 'lanthanoids', 'actinoids'] },
          { name: 'Co-ordination Compounds', topics: ['Nomenclature', 'isomerism', 'Werner’s theory', 'VBT', 'CFT'] },
          { name: 'Environmental Chemistry', topics: ['Pollution', 'green chemistry'] },
          { name: 'Purification and Characterization of Organic Compounds', topics: ['Qualitative and quantitative analysis'] },
          { name: 'Some Basic Principles of Organic Chemistry', topics: ['Nomenclature', 'isomerism', 'electronic effects'] },
          { name: 'Hydrocarbons', topics: ['Alkanes', 'alkenes', 'alkynes', 'aromatic hydrocarbons'] },
          { name: 'Organic Compounds Containing Halogens', topics: ['Haloalkanes', 'haloarenes'] },
          { name: 'Organic Compounds Containing Oxygen', topics: ['Alcohols', 'phenols', 'ethers', 'aldehydes', 'ketones', 'carboxylic acids'] },
          { name: 'Organic Compounds Containing Nitrogen', topics: ['Amines', 'diazonium salts', 'cyanides', 'isocyanides'] },
          { name: 'Polymers', topics: ['Classification', 'types of polymerization'] },
          { name: 'Biomolecules', topics: ['Carbohydrates', 'proteins', 'vitamins', 'nucleic acids'] },
          { name: 'Chemistry in Everyday Life', topics: ['Drugs', 'chemicals in food', 'cleansing agents'] },
        ],
      },
      {
        name: 'Mathematics',
        chapters: [
          { name: 'Sets, Relations and Functions', topics: ['Sets and their representations', 'relations', 'functions'] },
          { name: 'Complex Numbers and Quadratic Equations', topics: ['Complex numbers', 'quadratic equations'] },
          { name: 'Matrices and Determinants', topics: ['Matrices', 'determinants', 'system of linear equations'] },
          { name: 'Permutations and Combinations', topics: ['Permutations', 'combinations'] },
          { name: 'Mathematical Induction', topics: ['Principle of Mathematical Induction'] },
          { name: 'Binomial Theorem and Its Simple Applications', topics: ['Binomial theorem for positive integral indices'] },
          { name: 'Sequences and Series', topics: ['Arithmetic and Geometric progressions', 'summation of series'] },
          { name: 'Limit, Continuity and Differentiability', topics: ['Limits', 'continuity', 'differentiability'] },
          { name: 'Integral Calculus', topics: ['Indefinite integrals', 'definite integrals', 'properties of definite integrals'] },
          { name: 'Differential Equations', topics: ['Ordinary differential equations', 'their order and degree'] },
          { name: 'Co-ordinate Geometry', topics: ['Straight lines', 'circles', 'conic sections'] },
          { name: 'Three Dimensional Geometry', topics: ['Coordinates of a point in space', 'distance between two points', 'section formula', 'direction ratios and direction cosines'] },
          { name: 'Vector Algebra', topics: ['Vectors and scalars', 'addition of vectors', 'scalar and vector products'] },
          { name: 'Statistics and Probability', topics: ['Measures of dispersion', 'probability'] },
          { name: 'Trigonometry', topics: ['Trigonometrical identities and equations', 'trigonometrical functions', 'heights and distances'] },
          { name: 'Mathematical Reasoning', topics: ['Statements', 'logical operations'] },
        ],
      },
    ],
  },
};
